apiVersion: v1
kind: Service
metadata:
  name: simple-ecommerce
  labels:
    app: simple-ecommerce
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
   app: simple-ecommerce
