controller:
  # ingress:
  #   enabled: true
  #   apiVersion: networking.k8s.io/v1
  #   hostName: jenkins.3.67.0.140.nip.io
  imagePullPolicy: IfNotPresent
  installPlugins:
    - kubernetes:1.30.6
    - workflow-aggregator:2.6
    - git:4.10.0
    - configuration-as-code:1.54
    - blueocean:1.25.1
    - role-strategy:3.2.0
  serviceType: LoadBalancer